### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by angelozehr** [skoval/deuce#3]
Hi Stephanie

Thanks for this compilation! What a great and huge collection of useful data!
I am not sure, how to use it, though.

I executed the two commands
`library(devtools)`
`install_github("skoval/deuce")`
And the download worked perfectly.

But how do I now access the data and it's description?

On my Ubuntu I went to my R folder (which is in the home directory) and found the package `deuce` there. In it lay the RData files which I can open in my RStudio.
But for example in the R folder I do not find the R files with the data description as I expected it, viewing the github repo online.

Furthermore when I open for example the `atp_strength.Rdata` I find the available data there but it does not match the data description.
RStudio says my variable `atp_strength` has 288478 rows and 27 columns.
The [data description](https://github.com/skoval/deuce/blob/master/R/atp_strength.R) says that there should be 1,259,206 rows and 19 variables.

The table looks correct. There is data available from 1968 to `2016-01-18` (very neat, thx for that!) but I was just confused as it does not match the description in the R file on github.

Can you help me out?
When I have everything up and running I'd be happy to contribute a manual of the steps I took.
btw: Is there a list of data sources you used for this compilation?

---
A quick additional remark: I just realized that the variable atp_elo matches the [data description](https://github.com/skoval/deuce/blob/master/R/atp_strength.R)

**Comment by skoval** [comment]
Thank you for your interest in deuce.

I've just performed a commit that I hope has addressed the manual/data inconsistencies.

Also, please have a look at new Readme file. It has some more description of some of the basic contents and provides a few small examples. It is brief but I hope it provides additional help.

**Comment by angelozehr** [comment]
Thx! That really helped!
