### ISSUE TITLE
Error in package install?

### ISSUE THREAD

**Issue by TMBish** [skoval/deuce#5]
Really awesome package.

Think something may have been broken with the most recent update? 

I'm getting this error when installing from source (because `install_github` is erroring out without helpful error messaging):

```
Error: package or namespace load failed for 'deuce' in namespaceExport(ns, exports):
 undefined exports: serve_loss_importance, return_loss_importance
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'XXX/3.5/deuce'
In R CMD INSTALL
Warning in install.packages :
  installation of package 'XXX/deuce-master/deuce-master' had non-zero exit status
```

Potentially a problem in the `serve_loss_importance` / `return_loss_importance` Roxygen?

**Comment by skoval** [comment]
Yes, export needed to be added to the loss_importance functions. Thx. Should be corrected now.
