### ISSUE TITLE
missing functions in 'in_match_win.R'

### ISSUE THREAD

**Issue by kvanallen** [skoval/deuce#7]
There are five functions used in the file 'in_match_win.R' which are not defined anywhere else in the package. I believe they are trying to be used to create a look-up table.  They are currently showing up in the check as undocumented code objects and undocumented data sets. Any suggestions how I should go about this? Could they be located locally? 

Five functions are: 

- ‘advantage_matches’ 

- ‘regular_game_matrices’ 

- ‘set_win_advantage’ 

- ‘set_win_tiebreak’

- ‘tiebreak_game_matrices

**Comment by skoval** [comment]
These objects are internal data that are stored in R/sysdata.Rda. These are intended for use by the in_match_win function and not for use by the user. Hadley Wickham [suggested sysdata](http://r-pkgs.had.co.nz/data.html) as an option in this case. What would we need to do for this to be "documented" while still being internally stored?

**Comment by kvanallen** [comment]
Oh I see now! Thank you. I'll correct the documentation on that and let you know!

**Comment by kvanallen** [comment]
I think this was a mix-up on my part, I moved it `sysdata.Rda` back to the `R` folder and the issue went away!
